services:
  mongo:
    image: mongo:7.0
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 60s
      timeout: 60s
      retries: 5
      start_period: 60s
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - /persistent/mongod.conf:/etc/mongod.conf
      - mongo_data:/data/mongodb
    ports:
      - "27017:27017"
    networks:
      - nmis_net
  nmis:
    image: public.ecr.aws/n2x4v8j4/firstwave/nmis9_omk:v1.9
    restart: always
    environment:
      NMIS_DB_USERNAME: ${NMIS_DB_USERNAME}
      NMIS_DB_PASSWORD: ${NMIS_DB_PASSWORD}
      NMIS_DB_SERVER: ${NMIS_DB_SERVER}
      NMIS_SERVER_NAME: ${NMIS_SERVER_NAME}
    depends_on:
      - mongo
    volumes:
      - log_data:/usr/local/nmis9/logs
      - var_data:/usr/local/nmis9/var
      - conf_data:/usr/local/nmis9/conf
      - database_data:/usr/local/nmis9/database
      # You can mount your own config files into volumes in the container but 
      # you must ensure that the db config details match whats in this compose file
      - /persistent/Config.nmis:/usr/local/nmis9/conf/Config.nmis
      - /persistent/opCommon.json:/usr/local/omk/conf/opCommon.json
      - omk_log_data:/usr/local/omk/log
      - omk_var_data:/usr/local/omk/var
      - omk_conf_data:/usr/local/omk/conf
      # - ./persistent:/persistent
      # - ./app_conf/opLicense.json:/usr/local/omk/conf/opLicense.json
    ports:
      - "8080:8080"
      - "8042:8042"
      - "2055:2055/udp"
      - "161:161/udp"
      - "25:25"
    networks:
      - nmis_net
  redis:
    image: redis:6.0.16
    restart: always
    environment:
      REDIS_PASSWORD: example
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - nmis_net
networks:
  nmis_net:
volumes:
  log_data:
  var_data:
  conf_data:
  database_data:
  omk_log_data:
  omk_var_data:
  omk_conf_data:
  mongo_data:
  redis_data: