# the omkd Daemon needs to be reloaded to reopen the log files
# if opEvents is installed (and new enough to hold logs open), then the opeventsd also needs to be reloaded; 
# ditto opconfigd;
# if opFlow is installed, then the opflowd also needs to be reloaded

/var/lib/docker/volumes/nmis-suite_omk_log_data/_data/*.log
{
        rotate 15
        daily
        maxsize 250M
        dateext
        dateformat -%Y-%m-%d
        compress
        delaycompress
        missingok
        notifempty
        sharedscripts
        su root root
        postrotate
           docker exec nmis-suite-nmis-1 /usr/sbin/service omkd restart >/dev/null 2>&1
           docker exec nmis-suite-nmis-1 /usr/sbin/service opeventsd restart >/dev/null 2>&1
           docker exec nmis-suite-nmis-1 /usr/sbin/service opconfigd restart >/dev/null 2>&1
           docker exec nmis-suite-nmis-1 /usr/sbin/service opchartsd restart >/dev/null 2>&1
        endscript
}