/var/lib/docker/volumes/nmis-suite_httpd_log/_data/*.log {
    daily
    rotate 6
    missingok
    notifempty
    compress
    delaycompress
    sharedscripts
    postrotate
       docker kill -s SIGUSR1 nmis-suite-httpd-1 >/dev/null 2>&1
    endscript
}