# logrotate configuration file
#
# PLEASE NOTE: this logrotation file is for logrotate version 3.8.0 and
# newer! 3.7.x doesn't have the su option (or enforce it...)

# cisco logs and nmis poller event logs are syslog-controlled,
# thus the syslog daemon needs to be informed of the rotation
"/var/lib/docker/volumes/nmis-suite_nmis_log_data/_data/ciscopix.log"
"/var/lib/docker/volumes/nmis-suite_nmis_log_data/_data/cisco.log"
"/var/lib/docker/volumes/nmis-suite_nmis_log_data/_data/poller_event.log" {
    missingok
    notifempty
    sharedscripts
    rotate 20
    weekly
    compress
    su root root
    delaycompress
}

# trap.log is reopened automatically, no long-lived processes attached
# audit, auth, event logs are reopened automaticaly at this time
"/var/lib/docker/volumes/nmis-suite_nmis_log_data/_data/trap.log"
"/var/lib/docker/volumes/nmis-suite_nmis_log_data/_data/audit.log"
"/var/lib/docker/volumes/nmis-suite_nmis_log_data/_data/auth.log"
"/var/lib/docker/volumes/nmis-suite_nmis_log_data/_data/event.log" {
    missingok
    notifempty
    rotate 20
    weekly
    compress
    su root root
    delaycompress
}

# the nmisd log are not auto-reopened, ditto fping
# nmisd controls its fping worker, so one signal is sufficient
"/var/lib/docker/volumes/nmis-suite_nmis_log_data/_data/nmis.log"
"/var/lib/docker/volumes/nmis-suite_nmis_log_data/_data/fping.log" {
    missingok
    notifempty
    sharedscripts
    rotate 20
    weekly
    compress
    delaycompress
    su root root
    postrotate
        docker exec nmis-suite-nmis-1 /usr/local/nmis9/bin/nmisd act=stop >/dev/null 2>&1
        docker exec nmis-suite-nmis-1 /usr/local/nmis9/bin/nmisd foreground=1 debug=1 >/dev/null 2>&1 &
    endscript
}