/var/lib/docker/volumes/nmis-suite_mongo_log/_data/mongod.log {
  daily
  maxsize 500M
  rotate 6
  missingok
  compress
  delaycompress
  notifempty
  create 640 999 999
  sharedscripts
  postrotate
    docker exec nmis-suite-mongo-1 sudo kill -SIGUSR1 $(pidof mongod) >/dev/null 2>&1||:
  endscript
}