# the omkd Daemon needs to be reloaded to reopen the log files
# if opEvents is installed (and new enough to hold logs open), then the opeventsd also needs to be reloaded; 
# ditto opconfigd;
# if opFlow is installed, then the opflowd also needs to be reloaded

/var/lib/docker/volumes/nmis-suite_omk_log_data/_data/*.log
{
        rotate 15
        daily
        maxsize 250M
        dateext
        dateformat -%Y-%m-%d
        compress
        delaycompress
        su 10001 10001
        create 0660 10001 10001
        missingok
        notifempty
        sharedscripts
        postrotate
                { [ -e /etc/systemd/system/omkd.service      ] && systemctl restart omkd      >/dev/null; } || { { [ -x /etc/init.d/omkd      ]                                          && service omkd      reload >/dev/null; } || true; }
                { [ -e /etc/systemd/system/opeventsd.service ] && systemctl restart opeventsd >/dev/null; } || { { [ -x /etc/init.d/opeventsd ] && grep -Fq reload /etc/init.d/opeventsd && service opeventsd reload >/dev/null; } || true; }
                { [ -e /etc/systemd/system/opflowd.service   ] && systemctl restart opflowd   >/dev/null; } || { { [ -x /etc/init.d/opflowd   ] && grep -Fq reload /etc/init.d/opflowd   && service opflowd   reload >/dev/null; } || true; }
                { [ -e /etc/systemd/system/opconfigd.service ] && systemctl restart opconfigd >/dev/null; } || { { [ -x /etc/init.d/opconfigd ] && grep -Fq reload /etc/init.d/opconfigd && service opconfigd reload >/dev/null; } || true; }
                { [ -e /etc/systemd/system/opchartsd.service ] && systemctl restart opchartsd >/dev/null; } || { { [ -x /etc/init.d/opchartsd ] && grep -Fq reload /etc/init.d/opchartsd && service opchartsd reload >/dev/null; } || true; }
        endscript
}