#!/bin/sh
# warn the user regarding beta release,

# find out where we are, and get common functions
SCRIPTPATH=${0%/*}
. $SCRIPTPATH/common_functions.sh

printBanner "This is a beta release!"

cat <<EOF
Version $VERSION of $PRODUCT is an beta release
and not ready for production use. 

Though unlikely, data loss and various faults are 
certainly possible with this early release.

If you want to continue with the installation now, 
please type "CONTINUE" at the following prompt; all other inputs 
will cause the installer to abort.

EOF

input_text "Your choice? " "8671"
if [ "$RESPONSE" = "CONTINUE" ]; then
		echolog "User agrees to beta warning.."
		exit  0;
else
		echolog  "Aborting upgrade, as instructed."
		exit 1;
fi
exit 0
