#!/bin/sh
# warn the user regarding alpha level release,
# and bail out for non-debian-9 releases

# find out where we are, and get common functions
SCRIPTPATH=${0%/*}
. $SCRIPTPATH/common_functions.sh

flavour
if [ "$OSFLAVOUR" != "debian" -o "$OS_MAJOR" != 9 ]; then
		printBanner "Unsupported OS!"
		cat <<EOF
This version of $PRODUCT can only be installed on 
Debian 9 aka Debian Stretch. Your OS $OSFLAVOUR $OS_MAJOR
is not supported.

EOF
		exit 1;
fi

printBanner "This is an alpha release!"

cat <<EOF
Version $VERSION of $PRODUCT is an alpha release
and not ready for production use. 

Though unlikely, data loss and various faults are 
certainly possible with this early release.

If you want to continue with the installation now, 
please type "CONTINUE" at the following prompt; all other inputs 
will cause the installer to abort.

EOF

input_text "Your choice? "
if [ "$RESPONSE" = "CONTINUE" ]; then
		echolog "User agrees to alpha warning.."
		exit  0;
else
		echolog  "Aborting upgrade, as instructed."
		exit 1;
fi
exit 0
