#!/bin/sh
# create some directories

# find out where we are, and get common functions
SCRIPTPATH=${0%/*}
. $SCRIPTPATH/common_functions.sh

echolog "Updating file paths"

# move debug.pl
if [ -f "${TARGETDIR}/cgi-bin/debug.pl" ] || [ -L "${TARGETDIR}/cgi-bin/debug.pl" ]; then
	execPrint mv -f "${TARGETDIR}/cgi-bin/debug.pl" "${TARGETDIR}/admin/debug.pl";
fi;

exit 0
