#!/bin/sh
# minimal config file priming from the conf-default directory to conf

# find out where we are, and get common functions
SCRIPTPATH=${0%/*}
. $SCRIPTPATH/common_functions.sh

if [ -n "$CLEANSLATE" ]; then
		printBanner "Installing default config files"

		# copy only the absolute minimum necessary, the rest can stay in conf-default
		for i in Config.nmis users.dat; do
				execPrint "cp -va $TARGETDIR/conf-default/$i $TARGETDIR/conf/"
		done
		execPrint "$TARGETDIR/admin/patch_config.pl -b $TARGETDIR/conf/Config.nmis '/directories/<nmis_base>'=$TARGETDIR"
else
		# upgrade case
		printBanner "Updating (missing) configuration files"

		# copy only missing utterly crucial files
		# -n/--noclobber vital here, and no recursion
		execPrint "cp -van $TARGETDIR/conf-default/users.dat $TARGETDIR/conf-default/Config.nmis  $TARGETDIR/conf/"

		execPrint "$TARGETDIR/admin/patch_config.pl -b $TARGETDIR/conf/Config.nmis /system/keep_event_history=false /expiration/purge_event_after=604800 /system/network_viewNode_field_list=nodestatus,outage,sysName,host_addr,host_addr_backup,group,customer,location,businessService,serviceStatus,notes,nodeType,nodeModel,polling_policy,sysUpTime,sysLocation,sysContact,sysDescr,ifNumber,last_ping,last_collect,last_update,nodeVendor,sysObjectName,roleType,netType /system/non_stateful_events='Node Configuration Change, Node Configuration Change Detected, Node Reset, NMIS runtime exceeded' '/directories/<nmis_base>'=$TARGETDIR"
fi

exit 0
