#!/bin/sh
# minimal config file priming from the conf-default directory to conf 

# find out where we are, and get common functions
SCRIPTPATH=${0%/*}
. $SCRIPTPATH/common_functions.sh

if [ -n "$CLEANSLATE" ]; then
		printBanner "Installing default config files"

		# copy only the absolute minimum necessary, the rest can stay in conf-default
		for i in Config.nmis users.dat; do
				execPrint "cp -va $TARGETDIR/conf-default/$i $TARGETDIR/conf/"
		done
else
		# upgrade case
		printBanner "Updating any missing configuration files"

		# copy only missing utterly crucial files
		# -n/--noclobber vital here, and no recursion
		execPrint "cp -van $TARGETDIR/conf-default/users.dat $TARGETDIR/conf/"
fi

exit 0


