#!/bin/sh
# shut down any running nmisd before performing an upgrade

# find out where we are, and get common functions
SCRIPTPATH=${0%/*}
. $SCRIPTPATH/common_functions.sh

if [ -x "/etc/init.d/nmis9d" ]; then
		printBanner "Stopping NMIS9 Daemons"
		execPrint service nmis9d stop
fi
exit 0
