#!/bin/sh
# perform config updates on upgrade

# find out where we are, and get common functions
SCRIPTPATH=${0%/*}
. $SCRIPTPATH/common_functions.sh

if [ -n "$CLEANSLATE" ]; then
		logmsg "No config updates required"
		exit 0
fi

printBanner "Config file updates"

# main config first...
execPrint $TARGETDIR/admin/updateconfig.pl $TARGETDIR/conf-default/Config.nmis $TARGETDIR/conf/Config.nmis

# ...then the crucial auth-related files (if changed ones exist)
for i in POSSIBLE in Users.nmis Access.nmis PrivMap.nmis; do
		if [ -f "$TARGETDIR/conf/$POSSIBLE" ]; then
				execPrint $TARGETDIR/admin/updateconfig.pl "$TARGETDIR/conf-default/$POSSIBLE" "$TARGETDIR/conf/$POSSIBLE"
		fi
done


# then look for custom files, produce diffs in /tmp and report them to the user
printBanner "Looking for custom configuration files..."

DIFFS=/tmp/custom_configuration_files
# ...then all .nmis files
for MAYBECUSTOM in `cd $TARGETDIR/conf-default; ls *.nmis`; do
		[ -f "$TARGETDIR/conf/$MAYBECUSTOM" ] || continue;
		echo "Checking $MAYBECUSTOM" >> $DIFFS
		# exits 0 on no differences
		if ! $TARGETDIR/admin/diffconfigs.pl "$TARGETDIR/conf-default/$MAYBECUSTOM" "$TARGETDIR/conf/$MAYBECUSTOM" >>$DIFFS 2>&1; then
				FOUNDDIFFS="$FOUNDDIFFS $MAYBECUSTOM";
		fi
done

# ...and the same for plugins and the scripts
for MAYBE in `cd $TARGETDIR; ls conf-default/plugins/*`; do
		CUSTOM="$TARGETDIR/conf/plugins/"`basename "$MAYBE"`

		echo "Checking $MAYBE" >> $DIFFS
		if [ -e "$CUSTOM" ] && ! diff -u $MAYBE $CUSTOM >> $DIFFS 2>&1; then
				FOUNDDIFFS="$FOUNDDIFFS $MAYBE"
		fi
done
for MAYBE in `cd $TARGETDIR; ls conf-default/scripts/*`; do
		CUSTOM="$TARGETDIR/conf/scripts/"`basename "$MAYBE"`

		echo "Checking $MAYBE" >> $DIFFS
		if [ -e "$CUSTOM" ] && ! diff -u $MAYBE $CUSTOM >> $DIFFS 2>&1; then
				FOUNDDIFFS="$FOUNDDIFFS $MAYBE"
		fi
done

if [ -n "$FOUNDDIFFS" ]; then
		
		printBanner "Non-upgradeable customm confir files detected"
		cat <<EOF
The installer has detected the following custom configuration files 
that require manual updating:

$FOUNDDIFFS

The file $DIFFS has more details about the actual differences.

To resolve this issue, you can manually merge your custom files
with the appropriate new data from conf-default, 
or remove the custom files so that NMIS falls back to the defaults.

EOF
		input_ok "Hit <Enter> when ready to continue: "
else
		echo "No custom config files with differences were encountered."
		logmsg "No custom config files with differences were encountered."
		rm -f $DIFFS
fi

exit 0
