#!/bin/sh
# start the nmis9 daemon, unlock nmis

# find out where we are, and get common functions
SCRIPTPATH=${0%/*}
. $SCRIPTPATH/common_functions.sh

printBanner "Starting NMIS 9 Daemon"

if [ -x /etc/init.d/nmis9d ]; then
		echolog "Starting NMIS9 Daemon"
		execPrint "service nmis9d start"
elif [ -f /etc/systemd/system/nmis9d.service ]; then
		echolog "Starting NMIS9 Daemon"
		execPrint "systemctl start nmis9d"
else
		echolog "No init script or service file for the NMIS9 daemon on the system, cannot start it until that is installed as /etc/init.d/nmis9d or /etc/systemd/system/nmis9d.service"
		input_ok "Hit <Enter> when ready to continue: "
fi

# remove the lock file, installer status file and  stale selftest file
rm -f /tmp/nmis_install_running $TARGETDIR/conf/NMIS_IS_LOCKED $TARGETDIR/var/nmis_system/selftest.json

exit 0
