#!/bin/sh
# ensure nmis user exists

# find out where we are, and get common functions
SCRIPTPATH=${0%/*}
. $SCRIPTPATH/common_functions.sh

# guesses os flavour, sets OSFLAVOUR
flavour

if [ "$OSFLAVOUR" = "redhat" ]; then
		WEBGRP=apache
		GRPTOOL="usermod -G nmis apache"
		USERTOOL="useradd"
elif [ "$OSFLAVOUR" = "debian" -o "$OSFLAVOUR" = "ubuntu" ]; then
		WEBGRP=www-data
		GRPTOOL="adduser www-data nmis"
		USERTOOL="adduser --no-create-home --shell /bin/false --gecos NMIS --disabled-login --quiet"
fi

printBanner "Adjusting users, ownerships and permissions"

# nmis doesn't work w/o user
if ! id nmis >/dev/null 2>&1; then
		echolog "Adding NMIS user"
		execPrint $USERTOOL nmis
fi

# and apache needs to be able to access stuff
echolog "Adding web user to NMIS group"
execPrint $GRPTOOL


# the web user should in most scenarios be able to write to the users.dat password file
if [ -f "$TARGETDIR/conf/users.dat" ]; then
		execPrint chgrp $WEBGRP $TARGETDIR/conf/users.dat
		execPrint chmod g+rw $TARGETDIR/conf/users.dat
fi



# encryption of secrets
SEED_DIR='/usr/local/etc/opmantek';
SEED_FILE="${SEED_DIR}/seed.txt";

# Only if seed file does not yet exist:
if [ ! -e "${SEED_FILE}" ]; then
	if [ ! -e "${SEED_DIR}" ]; then
		execPrint "mkdir -p ${SEED_DIR}";
	fi;
	execPrint "chmod 0770 ${SEED_DIR}";
	execPrint "chown ${WEBGRP}:nmis ${SEED_DIR}";

	# OMK-8690: OMK::Common::_make_seed() function is the basis of this perl code:
	SEEDLENGTH=256;

	SEED="$(perl -e 'use strict;use warnings;use diagnostics;my $seedlength='"${SEEDLENGTH}"';my @charset=(("A".."Z"),("a".."z"),(0..9));my $range=$#charset+1;my $seed;for(1..$seedlength){$seed .= $charset[int(rand($range))];};if(length($seed)!=$seedlength){die "seed length of ".length($seed)." not equal to $seedlength characters. Aborting ...\n";$seed="";exit 1;};print "$seed\n";' 2>&1)";
	# Make sure we have the correct length seed before writing it:
	if [ "${#SEED}" != "${SEEDLENGTH}" ]; then
		echo "seed length ${#SEED} incorrect. Aborting ...";
		exit 1;
	fi;

	# TO PROTECT OUR secret WE NEED TO TURN OFF xtrace IN THIS SCRIPT IF ON - REINSTATE xtrace ON EXIT WHERE IT WAS SET ON ENTRY TO THIS SCRIPT:
	if set -o|grep xtrace|grep -q on; then
		SETUP_EXECPRINTSECURE_XTRACE_ON=1;
	else
		SETUP_EXECPRINTSECURE_XTRACE_ON=0;
	fi;
	set +x;

	# Write seed and set owner, group and permissions:
	execPrint "echo ${SEED} > ${SEED_FILE}";

	# REINSTATE xtrace ON EXIT WHERE IT WAS SET ON ENTRY TO THIS SCRIPT
	if [ "${SETUP_EXECPRINTSECURE_XTRACE_ON}" -eq 1 ]; then
		set -x;
	fi;

	execPrint "chown ${WEBGRP}:nmis ${SEED_FILE}";
	execPrint "chmod 0440 ${SEED_FILE}";
fi;



exit 0


