#!/bin/sh
# setup a cron job for NMIS

# find out where we are, and get common functions
SCRIPTPATH=${0%/*}
. $SCRIPTPATH/common_functions.sh

printBanner "NMIS Scheduling Setup"

SRCFILE=$TARGETDIR/conf-default/cron.d/nmis9
DESTFILE=/etc/cron.d/nmis9

# be polite, ask before doing anything harsh
if [ ! -f $DESTFILE ] || ! diff -q $DESTFILE $SRCFILE; then
		if input_yn "Ok to install new NMIS cron schedule?" ; then
				execPrint cp -af $SRCFILE $DESTFILE
				echolog "Created schedule in $DESTFILE."
		else
				echolog "Not creating or overwriting $DESTFILE, as directed."
				cat <<EOF

NMIS absolutely requires some scheduling setup to work correctly.
An example default Cron schedule is available in
$SRCFILE, which should be installed as $DESTFILE after
any local customisations.

EOF
				input_ok "Hit <Enter> when ready to continue: "
		fi
else
		echolog "NMIS's cron schedule is uptodate."
fi

exit 0


