#!/bin/sh
# clean up some of the earlier releases' leftovers

# find out where we are, and get common functions
SCRIPTPATH=${0%/*}
. $SCRIPTPATH/common_functions.sh

ONLYFRESH=$TARGETDIR/conf-default
if [ -d "$ONLYFRESH" ]; then
		execPrint "rm -rf $ONLYFRESH"
fi

GONER=$TARGETDIR/install
if [ -d "$GONER" ]; then
		echolog "Adjusting for conf-default (instead of install)"
		execPrint "rm -rf $GONER"
fi

# move debug.pl
DEBUG_SRC="${TARGETDIR}/cgi-bin/debug.pl";
if [ -f "${DEBUG_SRC}" ] || [ -L "${DEBUG_SRC}" ]; then
		DEBUG_TGT="${TARGETDIR}/admin/debug.pl";

		echolog "Moving '${DEBUG_SRC}' to '${DEBUG_TGT}'";
		execPrint mkdir -p "${TARGETDIR}/admin";
		execPrint mv -f "${DEBUG_SRC}" "${DEBUG_TGT}";
fi;


exit 0
