#!/bin/sh
# check the EOS (encryption-of-secrets) product compatibility
#
# TODO
# using opmantek.pl to fetch versions can be slow - in future we should have
# a faster way to fetch versions

# find out where we are, and get common functions
SCRIPTPATH=${0%/*}
. $SCRIPTPATH/common_functions.sh
. $SCRIPTPATH/common_mongodb.sh
. $SCRIPTPATH/common_repos.sh

printBanner "Checking EOS (encryption-of-secrets) product compatibility..."

status_msg=`$TARGETDIR/bin/nmis-cli act=is-eos-available | grep -v 'Checking'`
EOSOK=$?
if [ ! -z "$OMK_INSTALLED_PRODUCTS" ]; then
	$TARGETDIR/bin/nmis-cli act=check-eos >/dev/null 2>&1
	EOSENABLED=$?
fi

# Give notice if this is the last product to be upgraded
# Give warning if this is NOT the last product to be upgraded
if [ 0$EOSOK -eq 1 ];then
	echolog "*** Notice ***"
	echolog ""
	if [ -z "$OMK_INSTALLED_PRODUCTS" ]; then
		echolog "  This appears to be a fresh install of your first FirstWave product."
	else
		echolog "  You have now upgraded all installed FirstWave products to allow encryption of secrets."
	fi
	echolog "  You can now enable encryption of secrets to make your products more secure."
	echolog ""
	echolog "$status_msg"
	echolog ""
	echolog ""
	echolog "  For more information see wiki https://community.opmantek.com/display/opCommon/Encryption+of+Secrets"
	echolog ""
	if [ -z "$OMK_INSTALLED_PRODUCTS" ]; then
		input_yn "Would you like to enable encryption of secrets in NMIS now?" "3419";
	elif [ -z "$OMK_INSTALLED_PRODUCTS" -o 0$EOSENABLED -eq 1 ]; then
		input_yn "Encryption is already enabled on you system, would you like to keep it enabled?" "3419";
	else
		input_ny "Would you like to enable encryption of secrets in NMIS now?" "3419";
	fi
	answer=$?
	if [ 0$answer -eq 0 ]; then
		echolog "Enabling encryption of secrets in NMIS, please wait..."
		#execPrint $TARGETDIR/bin/nmis-cli act=enable-eos
	else
		echolog "Not enabling encryption of secrets in NMIS as directed."
	fi
else
	echolog "*** Warning ***"
	echolog ""
	echolog "  You have upgraded to a version of product that allows encryption of secrets, however you cannot enable"
	echolog "  encryption of secrets until all installed FirstWave products are upgraded to allow encryption of secrets."
	echolog ""
	echolog "$status_msg"
	echolog ""
	echolog ""
	echolog "  For more information see wiki https://community.opmantek.com/display/opCommon/Encryption+of+Secrets"
	echolog ""
	input_ok "Hit <Enter> when ready to continue: ";
fi

exit 0
