#!/bin/sh
# check the EOS (encryption-of-secrets) product compatibility
#

# find out where we are, and get common functions
SCRIPTPATH=${0%/*}
. $SCRIPTPATH/common_functions.sh
. $SCRIPTPATH/common_mongodb.sh
. $SCRIPTPATH/common_repos.sh

# return 0 if eos enabled successfully, 1 if not
enable-eos() {
		return ! $TARGETDIR/bin/nmis-cli act=enable-eos ;
}


printBanner "Checking EOS (Encryption of Secrets) product compatibility..."

eos_status_msg=`$TARGETDIR/bin/nmis-cli act=is-eos-available`
EOSAVAILABLE=$?

if [ ! -z "$OMK_INSTALLED_PRODUCTS" ]; then
	$TARGETDIR/bin/nmis-cli act=check-eos >/dev/null 2>&1
	EOSENABLED=$?
fi

# Give notice if this is the last product to be upgraded
# Give warning if this is NOT the last product to be upgraded

if [ 0$EOSAVAILABLE -eq 0 ];then
    # EOS is NOT available
	echolog "*** Warning ***"
	echolog ""
	echolog "  You have upgraded to a version of NMIS that allows encryption of secrets, however you cannot enable"
	echolog "  encryption of secrets until all installed FirstWave products are upgraded to allow encryption of secrets."
	echolog ""
	echolog "$eos_status_msg"
	echolog ""
	echolog "  For more information see wiki https://community.opmantek.com/display/opCommon/Encryption+of+Secrets"
	echolog ""
	input_ok "Hit <Enter> when ready to continue: ";
else
	echolog "*** Notice ***"
	echolog ""
	if [ -z "$OMK_INSTALLED_PRODUCTS" ]; then
		echolog "  This appears to be a fresh install of your first FirstWave product."
	else
		echolog "  You have now upgraded all installed FirstWave products to allow encryption of secrets."
		echolog "  You can now enable encryption of secrets to make your products more secure."
	fi
	echolog ""
	echolog "$eos_status_msg"
	echolog ""
	echolog "  For more information see wiki https://community.opmantek.com/display/opCommon/Encryption+of+Secrets"
	echolog ""
	if [ -z "$OMK_INSTALLED_PRODUCTS" ]; then
		# This is a fresh install of NMIS and EOS is available
		echolog "Enabling encryption of secrets for FirstWave products, please wait..."
		execPrint enable-eos
	elif [ 0$EOSENABLED -eq 1 ]; then
		echolog "Encryption of secrets is already enabled on your system."
	else
		echolog "You can enable encryption of secrets using the command     sudo $TARGETDIR/bin/nmis-cli act=enable-eos";
	fi
	echolog ""
	input_ok "Hit <Enter> when ready to continue: ";
fi

exit 0
