package NMISNG::HTTPModelBuilder;

# Generate starter Common-*.nmis + Graph-*.nmis from a Prometheus
# /metrics body. Designed for one-shot use: operator points the
# CLI wrapper at a live exporter, the builder parses + groups +
# classifies the samples, and emits files under a draft directory.
# A README in the output lists the TODOs the operator must address
# (friendly titles, indexed-label confirmation, thresholds, DS-name
# truncations).
#
# The builder is library-form so the test can drive parse+group+emit
# pipelines without a live HTTP fetch.

use strict;
use warnings;
use NMISNG::PromText;
use Data::Dumper;
use File::Path qw(make_path);

# Histogram/summary suffixes that are aggregated into a single section.
my %TRIPLET_SUFFIX = ( '_bucket' => 1, '_sum' => 1, '_count' => 1 );

# RRD DS names are limited to 19 characters (rrdtool spec).
my $DS_NAME_MAX = 19;

# Visible DS cap on auto-generated graphs; extra DS still land in the
# RRD, just not on the graph. Operator splits a too-busy section into
# subgraphs by hand.
my $GRAPH_DS_CAP = 6;

# Palette for AREA/LINE/STACK in the generated graph option block.
my @PALETTE = qw(
	1E90FF 7CFC00 FFA500 FF6347 9370DB 20B2AA
	FFD700 FF1493 4682B4 32CD32 FF4500 8A2BE2
);

sub new
{
	my ($class, %args) = @_;
	my $self = {
		model_name    => $args{name}     // 'App',
		endpoint_name => $args{endpoint} // _to_snake($args{name} // 'app') . '_exporter',
		prefix_depth  => $args{prefix_depth} // 2,
		todos         => [],
	};
	return bless $self, $class;
}

# Public: build($body) -> hashref { common => ..., graphs => { name => ... },
#                                   todos => [...], notes => [...] }
sub build
{
	my ($self, $body) = @_;
	my ($samples, $errors) = NMISNG::PromText::parse_metrics($body);
	push @{$self->{todos}}, "parse: $_" for @$errors;

	my $groups = $self->_group($samples);
	my @sections;
	for my $g (@$groups)
	{
		push @sections, $self->_build_section($g);
	}

	return $self->_assemble(\@sections);
}

# Public: emit_files(out_dir => '...', result => $self->build(...))
# Writes Common-*.nmis, Graph-*.nmis files, README.md.
sub emit_files
{
	my ($self, %args) = @_;
	my $out    = $args{out_dir} or die "emit_files: out_dir required";
	my $result = $args{result}  or die "emit_files: result required";

	make_path($out) unless -d $out;

	my $name = $self->{model_name};

	# Common file.
	my $common_path = "$out/Common-Linux-HTTP-$name.nmis";
	_write_nmis($common_path, $result->{common});

	# Graph files.
	for my $gname (sort keys %{$result->{graphs}})
	{
		my $graph_path = "$out/Graph-$gname.nmis";
		_write_nmis($graph_path, $result->{graphs}{$gname});
	}

	# README listing the TODOs.
	my $readme = "$out/README.md";
	open(my $fh, '>', $readme) or die "cannot write $readme: $!";
	print $fh "# Scaffold output for $name\n\n";
	print $fh "Generated by `admin/build_http_model.pl`. These files are a\n";
	print $fh "starting point -- review the TODOs below, edit, then copy into\n";
	print $fh "`models-default/` (if shipping) or `models-custom/` (if site-\n";
	print $fh "specific) once they look right.\n\n";

	print $fh "## Add to a node\n\n";
	print $fh "1. Add an `http_endpoints` entry on the target node:\n";
	print $fh "   ```json\n";
	printf $fh "   { \"name\": \"%s\",\n", $self->{endpoint_name};
	print $fh "     \"scheme\": \"http\",\n";
	print $fh "     \"host\": \"<host>\",\n";
	print $fh "     \"port\": <port>,\n";
	print $fh "     \"auth\": { \"type\": \"none\" } }\n";
	print $fh "   ```\n";
	print $fh "2. Wire `Common-Linux-HTTP-$name.nmis` into the node's model.\n";
	print $fh "   See `docs/Model-Reference.md`, section 19, \"Wiring a\n";
	print $fh "   Common file into an existing model on a single node\".\n\n";

	if (@{$result->{todos}})
	{
		print $fh "## TODOs\n\n";
		my $i = 0;
		for my $todo (@{$result->{todos}})
		{
			$i++;
			print $fh "$i. $todo\n";
		}
		print $fh "\n";
	}

	if (@{$result->{notes}})
	{
		print $fh "## Notes\n\n";
		print $fh "- $_\n" for @{$result->{notes}};
		print $fh "\n";
	}

	close $fh;
	return { common => $common_path, readme => $readme };
}

# ------------------------------------------------------------------
# Grouping: collapse triplets, then group by metric-name prefix.
# ------------------------------------------------------------------

sub _group
{
	my ($self, $samples) = @_;

	# Pass A: find histogram/summary base names. PromText attaches
	# `type` to a sample only when the body has a `# TYPE <name>` line
	# matching the sample's exact name -- but real exporters emit the
	# TYPE on the BASE name (which has no samples of its own; only
	# _bucket/_sum/_count do). So we need both signals:
	#
	#   * structural: a `_bucket` sample with an `le` label is histo;
	#                 any sample with a `quantile` label is a summary.
	#   * annotated: a sample whose `type` is histogram/summary directly.
	#
	# If either signal fires, the base name is a triplet.
	my %is_triplet_base;
	for my $s (@$samples)
	{
		if (defined $s->{type}
			&& ($s->{type} eq 'histogram' || $s->{type} eq 'summary'))
		{
			my $base = _strip_triplet_suffix($s->{name}) // $s->{name};
			$is_triplet_base{$base} = $s->{type};
			next;
		}
		# Structural signals.
		if ($s->{name} =~ /_bucket$/ && $s->{labels} && exists $s->{labels}{le})
		{
			my $base = substr($s->{name}, 0, -length('_bucket'));
			$is_triplet_base{$base} //= 'histogram';
		}
		elsif ($s->{labels} && exists $s->{labels}{quantile})
		{
			# summary metrics' value samples don't have a suffix; their
			# siblings _sum and _count do. The base IS the sample's name.
			$is_triplet_base{$s->{name}} //= 'summary';
		}
	}

	# A `_sum`/`_count` sample whose stripped base matches a histogram
	# OR summary base is also part of the triplet -- already handled in
	# Pass B's lookup; nothing further to do here.

	# Pass B: bucket every sample into a section. Triplets go under
	# their base name; everything else is grouped by metric-name prefix.
	my %sections;
	for my $s (@$samples)
	{
		my $bname = _strip_triplet_suffix($s->{name});
		my $section_key;
		my $kind;
		my $base_name;

		if ($bname && $is_triplet_base{$bname})
		{
			$section_key = $bname;
			$kind        = $is_triplet_base{$bname};   # 'histogram' or 'summary'
			$base_name   = $bname;
		}
		elsif ($is_triplet_base{$s->{name}})
		{
			# Summary value samples have no suffix -- the sample IS the
			# triplet base. Group it with its _sum/_count siblings.
			$section_key = $s->{name};
			$kind        = $is_triplet_base{$s->{name}};
			$base_name   = $s->{name};
		}
		else
		{
			$section_key = _prefix_key($s->{name}, $self->{prefix_depth});
			$kind        = 'plain';
			$base_name   = $s->{name};
		}

		$sections{$section_key} //= {
			key          => $section_key,
			kind         => $kind,
			samples      => [],
			help_by_name => {},
			type_by_name => {},
		};
		push @{$sections{$section_key}{samples}}, $s;
		$sections{$section_key}{help_by_name}{$s->{name}} //= $s->{help}
			if defined $s->{help};
		$sections{$section_key}{type_by_name}{$s->{name}} //= $s->{type}
			if defined $s->{type};
	}

	# Stable order: by section key, alpha.
	return [ map { $sections{$_} } sort keys %sections ];
}

sub _strip_triplet_suffix
{
	my ($name) = @_;
	for my $sfx (keys %TRIPLET_SUFFIX)
	{
		return substr($name, 0, length($name) - length($sfx))
			if length($name) > length($sfx)
			&& substr($name, -length($sfx)) eq $sfx;
	}
	return undef;
}

sub _prefix_key
{
	my ($name, $depth) = @_;
	my @parts = split /_/, $name;
	$depth = scalar @parts if $depth > scalar @parts;
	$depth = 1             if $depth < 1;
	return join('_', @parts[0 .. $depth - 1]);
}

# ------------------------------------------------------------------
# Section construction: classify, derive DS, build section + graph.
# ------------------------------------------------------------------

sub _build_section
{
	my ($self, $group) = @_;

	# Classify: scalar / indexed / histogram-summary.
	my $classification = $self->_classify($group);

	# Per-DS items. For each unique metric in the group, decide what
	# the item key (DS name) is and whether match_labels is needed.
	my %items_by_metric;
	for my $s (@{$group->{samples}})
	{
		$items_by_metric{$s->{name}} //= [];
		push @{$items_by_metric{$s->{name}}}, $s;
	}

	my @items;
	my %ds_seen;
	for my $metric (sort keys %items_by_metric)
	{
		my $samples = $items_by_metric{$metric};
		my $type    = $group->{type_by_name}{$metric};
		my $opt     = (defined $type && $type eq 'counter') ? 'counter,0:U' : 'gauge,U:U';
		my $help    = $group->{help_by_name}{$metric};
		my $title   = _help_to_title($help);

		# For an indexed group, every metric gets one item per row IF
		# the rows are split by a label that is NOT the indexed var.
		# But typically each metric appears once per row, scoped only
		# by the indexed label -- so one item per metric is enough.
		# This mirrors how Common-Linux-HTTP-MongoDB.nmis is laid out.

		my $ds = _ds_name($metric, $group->{key}, \%ds_seen);
		if ($ds ne _ds_strip_only($metric, $group->{key}))
		{
			push @{$self->{todos}}, "DS '$ds' was truncated/uniquified from "
				. "'$metric' -- consider renaming for clarity (Common file, "
				. "section '$group->{key}')";
		}

		my %item = ( metric => $metric, option => $opt );
		$item{title} = $title if defined $title && length $title;
		push @items, [ $ds, \%item ];
	}

	# Build the section structure. Different shapes for scalar vs
	# indexed vs histogram.
	if ($classification->{kind} eq 'scalar')
	{
		return $self->_build_scalar_section($group, $classification, \@items);
	}
	elsif ($classification->{kind} eq 'indexed')
	{
		return $self->_build_indexed_section($group, $classification, \@items);
	}
	else    # histogram or summary
	{
		return $self->_build_histogram_section($group, $classification, \@items);
	}
}

sub _classify
{
	my ($self, $group) = @_;

	# Histogram/summary tagged in _group already.
	return { kind => 'histogram', type => $group->{kind} }
		if $group->{kind} eq 'histogram' || $group->{kind} eq 'summary';

	# For plain groups: are any samples labelled? If so, this is
	# almost certainly indexed.
	my %label_cardinality;    # label_name => count of distinct values
	my $any_labelled = 0;
	my %label_values;
	for my $s (@{$group->{samples}})
	{
		my $labels = $s->{labels} || {};
		for my $k (keys %$labels)
		{
			$any_labelled = 1;
			$label_values{$k}{$labels->{$k}} = 1;
		}
	}
	for my $k (keys %label_values)
	{
		$label_cardinality{$k} = scalar keys %{$label_values{$k}};
	}

	# Pick the label with highest cardinality as the suggested index.
	# Flag a TODO if multiple labels have similar high cardinality.
	if ($any_labelled)
	{
		my @sorted = sort { $label_cardinality{$b} <=> $label_cardinality{$a} }
			keys %label_cardinality;
		my $best   = $sorted[0];
		my $best_n = $label_cardinality{$best};
		my @runners
			= grep { $label_cardinality{$_} >= max($best_n - 1, 2) } @sorted[1 .. $#sorted];
		if (@runners)
		{
			push @{$self->{todos}},
				"Section '$group->{key}': multiple labels with similar cardinality "
				. "($best=$best_n, " . join(", ", map { "$_=$label_cardinality{$_}" } @runners)
				. "). Tool picked '$best' as 'indexed'; consider composite indexing "
				. "(`indexed => [...]`) if you want each (label1, label2) tuple to be "
				. "a distinct row.";
		}
		return {
			kind             => 'indexed',
			indexed          => $best,
			label_cardinality => \%label_cardinality,
		};
	}

	return { kind => 'scalar' };
}

sub max { my $m = shift; for (@_) { $m = $_ if $_ > $m } return $m }

# Sort `le` bucket boundaries numerically with +Inf last.
sub _le_sort
{
	return  1 if $a eq '+Inf';
	return -1 if $b eq '+Inf';
	return ($a + 0) <=> ($b + 0);
}

sub _build_scalar_section
{
	my ($self, $group, $cls, $items) = @_;

	# RRD-ID-safe topic name; this becomes the system.rrd key and the
	# database/type entry's filename stub.
	my $topic     = _topic_name($group->{key});
	my $graphtype = _graphtype_name($self->{model_name}, $group->{key});

	# Assemble the http_prom hash.
	my %http_prom = ('-common-' => { endpoint => $self->{endpoint_name} });
	for my $pair (@$items)
	{
		my ($ds, $item) = @$pair;
		$http_prom{$ds} = $item;
	}

	my $rrd_path = "/nodes/\$node/health/${topic}.rrd";

	return {
		kind        => 'scalar',
		group_key   => $group->{key},
		topic       => $topic,
		graphtype   => $graphtype,
		rrd_path    => $rrd_path,
		http_prom   => \%http_prom,
		items       => $items,
		section_def => {
			graphtype => $graphtype,
			http_prom => \%http_prom,
		},
	};
}

sub _build_indexed_section
{
	my ($self, $group, $cls, $items) = @_;

	my $section = _camel_section_name($self->{model_name}, $group->{key});
	my $graphtype = "$self->{model_name}-$section";
	my $rrd_path = "/nodes/\$node/health/" . _to_snake($section) . "-\$index.rrd";
	my $indexed = $cls->{indexed};

	# systemHealth.sys block (the inventory/header view).
	my %sys_http_prom = ('-common-' => { endpoint => $self->{endpoint_name} });
	# Index-self item so the indexed column shows the row's index value.
	$sys_http_prom{$indexed} = { title => _humanize($indexed) };
	for my $pair (@$items)
	{
		my ($ds, $item) = @$pair;
		# Defensive: don't overwrite the index-self entry if a metric
		# happens to share its name.
		next if $ds eq $indexed;
		# In sys block items are 'metric' + optional title (no option).
		my %sys_item = ( metric => $item->{metric} );
		$sys_item{title} = $item->{title} if defined $item->{title};
		$sys_http_prom{$ds} = \%sys_item;
	}

	my @ds_names = ($indexed, map { $_->[0] } grep { $_->[0] ne $indexed } @$items);
	my $headers = join(',', @ds_names);

	# systemHealth.rrd block (the data-collection view, what writes
	# the per-row RRD).
	my %rrd_http_prom = ('-common-' => { endpoint => $self->{endpoint_name} });
	for my $pair (@$items)
	{
		my ($ds, $item) = @$pair;
		next if $ds eq $indexed;
		$rrd_http_prom{$ds} = $item;
	}

	push @{$self->{todos}},
		"Section '$section' is indexed by '$indexed'. Consider whether "
		. "any rows should be filtered out via a `control` regex (see "
		. "Common-Linux-HTTP-MongoDB.nmis MongoDBDatabases for an example).";

	return {
		kind      => 'indexed',
		group_key => $group->{key},
		section   => $section,
		graphtype => $graphtype,
		rrd_path  => $rrd_path,
		indexed   => $indexed,
		headers   => $headers,
		items     => $items,
		sys_def   => {
			indexed   => $indexed,
			index_oid => $indexed,
			headers   => $headers,
			max_rows  => 256,
			http_prom => \%sys_http_prom,
		},
		rrd_def => {
			graphtype => $graphtype,
			indexed   => $indexed,
			http_prom => \%rrd_http_prom,
		},
	};
}

sub _build_histogram_section
{
	my ($self, $group, $cls, $items) = @_;

	# Histograms are best treated as a TODO -- the right shape is
	# operator-specific. We scaffold a section listing every triplet
	# member as an item, expand `_bucket` per `le` value so each bucket
	# is its own DS (otherwise multiple bucket samples would collide on
	# one DS), and let the operator decide whether to keep all `le`
	# items, drop them in favour of _sum/_count rate, or compute
	# percentiles in a plugin.
	my $section = _camel_section_name($self->{model_name}, $group->{key});
	my $graphtype = "$self->{model_name}-$section-Histogram";

	# Find the bucket samples and any distinct `le` values.
	my @bucket_samples;
	my %le_values;
	for my $s (@{$group->{samples}})
	{
		if ($s->{name} =~ /_bucket$/ && $s->{labels} && exists $s->{labels}{le})
		{
			push @bucket_samples, $s;
			$le_values{$s->{labels}{le}} = 1;
		}
	}

	# Reshape items: drop the collapsed bucket item, expand per-le.
	my %ds_seen;
	my @reshaped;
	my $bucket_metric;
	for my $pair (@$items)
	{
		my ($ds, $item) = @$pair;
		if ($item->{metric} =~ /_bucket$/)
		{
			$bucket_metric = $item->{metric};
			next;    # drop collapsed bucket; we'll re-add per-le below
		}
		# _sum / _count: keep as-is, but force counter option (cumulative).
		$item->{option} = 'counter,0:U';
		$ds_seen{$ds} = 1;
		push @reshaped, [$ds, $item];
	}
	if (defined $bucket_metric && %le_values)
	{
		for my $le (sort _le_sort keys %le_values)
		{
			my $bucket_ds = _ds_name("bucket_$le", '', \%ds_seen);
			push @reshaped, [
				$bucket_ds,
				{
					metric       => $bucket_metric,
					match_labels => { le => $le },
					option       => 'counter,0:U',
					title        => "Bucket le=$le",
				},
			];
		}
	}

	my %http_prom = ('-common-' => { endpoint => $self->{endpoint_name} });
	for my $pair (@reshaped)
	{
		my ($ds, $item) = @$pair;
		$http_prom{$ds} = $item;
	}
	$items = \@reshaped;

	push @{$self->{todos}},
		"Section '$section' wraps a Prometheus "
		. ($cls->{type} || 'histogram')
		. " ('$group->{key}'). The auto-scaffold expanded the buckets "
		. "into one DS per `le` value (" . (scalar keys %le_values)
		. " buckets) plus _sum and _count. Decide:\n"
		. "    a) Keep all bucket DS and graph the rate -- noisy but "
		. "complete.\n"
		. "    b) Drop the per-le bucket DS and graph rate(_sum) / "
		. "rate(_count) for average latency.\n"
		. "    c) Compute percentile in a plugin "
		. "(rate(_bucket)/rate(_count)). Out of scope for the "
		. "auto-scaffold.";

	# Treat as a scalar-shape section in the model file (no per-row
	# index). Operator can split into indexed if the histogram has a
	# 'method'/'route' label they care about.
	my $rrd_path = "/nodes/\$node/health/" . _to_snake($section) . ".rrd";

	return {
		kind        => 'histogram',
		group_key   => $group->{key},
		topic       => _topic_name($group->{key}),
		graphtype   => $graphtype,
		rrd_path    => $rrd_path,
		http_prom   => \%http_prom,
		items       => $items,
		section_def => {
			graphtype => $graphtype,
			http_prom => \%http_prom,
		},
	};
}

# ------------------------------------------------------------------
# Assembly: glue sections into a single Common file + per-section
# Graph files. Returns the in-memory shape that emit_files writes.
# ------------------------------------------------------------------

sub _assemble
{
	my ($self, $sections) = @_;

	my %db_type;
	my %sys_rrd;
	my %sh_sys;
	my %sh_rrd;
	my @nodegraph_entries;
	my %graphs;

	for my $sec (@$sections)
	{
		# database/type maps graphtype/topic name -> RRD path template.
		my $type_key
			= ($sec->{kind} eq 'indexed') ? $sec->{section} : $sec->{topic};
		$db_type{$type_key} = $sec->{rrd_path};

		if ($sec->{kind} eq 'indexed')
		{
			$sh_sys{$sec->{section}} = $sec->{sys_def};
			$sh_rrd{$sec->{section}} = $sec->{rrd_def};
		}
		else
		{
			$sys_rrd{$sec->{topic}} = $sec->{section_def};
		}

		push @nodegraph_entries, $sec->{graphtype};
		$graphs{$sec->{graphtype}} = $self->_build_graph($sec);
	}

	my %common = (
		database => { type => \%db_type },
	);
	$common{system} = {
		nodegraph => join(',', @nodegraph_entries),
		rrd       => \%sys_rrd,
	} if %sys_rrd || @nodegraph_entries;
	$common{systemHealth} = {
		(%sh_sys ? (sys => \%sh_sys) : ()),
		(%sh_rrd ? (rrd => \%sh_rrd) : ()),
	} if %sh_sys || %sh_rrd;

	# notes for the README -- non-actionable orientation.
	my @notes;
	push @notes, "Generated " . scalar(@$sections) . " sections from the "
		. "endpoint. " . scalar(@nodegraph_entries)
		. " graphtypes registered on the model.";
	if (grep { $_->{kind} eq 'indexed' } @$sections)
	{
		my @ix = grep { $_->{kind} eq 'indexed' } @$sections;
		push @notes, "Indexed sections still need their `sections` string "
			. "added to the model that includes this Common file -- the "
			. "Common file alone does not register them with "
			. "collect_systemhealth_info.";
	}

	return {
		common => \%common,
		graphs => \%graphs,
		todos  => $self->{todos},
		notes  => \@notes,
	};
}

# ------------------------------------------------------------------
# Graph file construction.
# ------------------------------------------------------------------

sub _build_graph
{
	my ($self, $sec) = @_;

	my @ds_names = map { $_->[0] } @{$sec->{items}};
	# For indexed sections the index-self item is in the systemHealth.sys
	# block but NOT in the rrd block, so it must not appear on the graph.
	if ($sec->{kind} eq 'indexed')
	{
		@ds_names = grep { $_ ne $sec->{indexed} } @ds_names;
	}
	my @visible = @ds_names[0 .. ($GRAPH_DS_CAP - 1 < $#ds_names ? $GRAPH_DS_CAP - 1 : $#ds_names)];

	my $heading = ($sec->{kind} eq 'indexed')
		? "$self->{model_name} $sec->{section}"
		: "$self->{model_name} " . _humanize($sec->{group_key});

	my @standard = ('--lower-limit', '0');
	my @small    = ('--lower-limit', '0');
	for my $ds (@visible)
	{
		push @standard, "DEF:$ds=\$database:$ds:AVERAGE";
		push @small,    "DEF:$ds=\$database:$ds:AVERAGE";
	}
	my $i = 0;
	for my $ds (@visible)
	{
		my $color = '#' . $PALETTE[$i % @PALETTE];
		my $shape = ($i == 0) ? 'AREA' : 'LINE1';
		my $label = ' ' . _humanize($ds);
		push @standard, "$shape:$ds$color:$label",
			"GPRINT:$ds:AVERAGE:Avg %8.2lf",
			"GPRINT:$ds:MAX:Max %8.2lf\\n";
		push @small,    "$shape:$ds$color:$label";
		$i++;
	}

	if (@ds_names > @visible)
	{
		push @{$self->{todos}},
			"Graph '$sec->{graphtype}' shows " . scalar(@visible)
			. " DS but the section has " . scalar(@ds_names)
			. ". The remaining DS are still recorded in the RRD; consider "
			. "splitting into multiple graph files or hand-picking which "
			. "DS to display.";
	}

	return {
		heading => $heading,
		title   => {
			standard => "\$node $heading - \$length from \$datestamp_start to \$datestamp_end",
			short    => "\$node $heading - \$length",
		},
		vlabel => {
			standard => 'Value',
			small    => 'val',
		},
		option => {
			standard => \@standard,
			small    => \@small,
		},
	};
}

# ------------------------------------------------------------------
# Naming helpers.
# ------------------------------------------------------------------

sub _ds_name
{
	my ($metric, $section_key, $seen) = @_;
	my $stripped = _ds_strip_only($metric, $section_key);
	my $ds       = substr($stripped, 0, $DS_NAME_MAX);

	# Dedup: if collision, append _2, _3, ... and re-truncate.
	if ($seen->{$ds})
	{
		my $n = 2;
		while (1)
		{
			my $suffix    = "_$n";
			my $maxbase   = $DS_NAME_MAX - length($suffix);
			my $candidate = substr($stripped, 0, $maxbase) . $suffix;
			if (!$seen->{$candidate})
			{
				$ds = $candidate;
				last;
			}
			$n++;
			last if $n > 99;    # give up; won't happen in practice
		}
	}
	$seen->{$ds} = 1;
	return $ds;
}

sub _ds_strip_only
{
	my ($metric, $section_key) = @_;
	my $stripped = $metric;
	# Strip the section prefix + one separating underscore if present.
	if (length($section_key) && index($metric, $section_key . '_') == 0)
	{
		$stripped = substr($metric, length($section_key) + 1);
	}
	# Replace remaining non-alphanum with underscores (RRD-safe).
	$stripped =~ s/[^A-Za-z0-9_]/_/g;
	$stripped = 'value' unless length $stripped;
	return $stripped;
}

sub _topic_name
{
	my ($key) = @_;
	my $t = lc $key;
	$t =~ s/[^a-z0-9]+/_/g;
	$t =~ s/_+/_/g;
	$t =~ s/^_|_$//g;
	return $t;
}

sub _camel_section_name
{
	my ($model, $key) = @_;
	my @parts = grep { length } split /_+/, $key;
	my $name = join('', map { ucfirst lc $_ } @parts);
	return $name;
}

sub _graphtype_name
{
	my ($model, $key) = @_;
	return "$model-" . _camel_section_name($model, $key);
}

sub _to_snake
{
	my ($s) = @_;
	$s = lc $s;
	$s =~ s/[^a-z0-9]+/_/g;
	$s =~ s/_+/_/g;
	$s =~ s/^_|_$//g;
	return $s;
}

sub _humanize
{
	my ($s) = @_;
	my @parts = grep { length } split /[_\W]+/, $s;
	return join(' ', map { ucfirst lc $_ } @parts);
}

sub _help_to_title
{
	my ($help) = @_;
	return undef unless defined $help && length $help;
	my $t = $help;
	$t =~ s/^Number of\s+//i;
	$t =~ s/^Metric for\s+//i;
	$t =~ s/^The\s+//i;
	$t =~ s/\.\s*$//;
	$t = ucfirst $t;
	# Truncate -- titles in the GUI are tight.
	$t = substr($t, 0, 60) if length($t) > 60;
	return $t;
}

# ------------------------------------------------------------------
# Serialization to .nmis.
# ------------------------------------------------------------------

sub _write_nmis
{
	my ($path, $hashref) = @_;
	open(my $fh, '>', $path) or die "cannot write $path: $!";
	print $fh "# Generated by admin/build_http_model.pl. Review TODO comments\n";
	print $fh "# in the README before installing.\n#\n";
	my $d = Data::Dumper->new([$hashref], ['hash']);
	$d->Sortkeys(1);
	$d->Indent(1);
	$d->Quotekeys(1);
	$d->Useqq(0);
	$d->Terse(0);
	# Data::Dumper prints `$hash = { ... };` for hashref; we want
	# `%hash = ( ... );` to match the canonical NMIS file shape. Convert.
	my $dump = $d->Dump;
	$dump =~ s/\A\$hash = \{/%hash = (/;
	$dump =~ s/\};\s*\z/);\n/;
	print $fh $dump;
	close $fh;
	return 1;
}

1;
