version: '3.4'

services:

  mongo:
    image: mongo:4.4
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 60s
      timeout: 60s
      retries: 5
      start_period: 60s
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/var/lib/mongodb

  redis:
    image: redis:6
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "example", "ping"]
      interval: 60s
      timeout: 60s
      retries: 5
      start_period: 60s
    command: ["redis-server", "--requirepass", "example"]
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: example

  nmis:
    image: nmis9
    environment:
      NMIS_DB_USERNAME: root
      NMIS_DB_PASSWORD: example
      NMIS_DB_SERVER: mongo
      NMIS_SERVER_NAME: example-host-1
      NMIS_CLUSTER_ID: 660f29ae-f150-4119-bf04-cd9296852449
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - log_data:/usr/local/nmis9/logs
      - var_data:/usr/local/nmis9/var
      - conf_data:/usr/local/nmis9/conf
      - database_data:/usr/local/nmis9/database
#Items mounted from app_conf into the container
#you'll need to make the dir/files
# add db creds to the opCommon.json and Config.nmis files
      - ./app_conf/Config.nmis:/usr/local/nmis9/conf/Config.nmis
      - ./app_conf/opCommon.json:/usr/local/omk/conf/opCommon.json
      - ./app_conf/opLicense.json:/usr/local/omk/conf/opLicense.json
    ports:
      - "8080:8080"
      - "8042:8042"

volumes:
  log_data:
  var_data:
  conf_data:
  database_data:
  mongo_data:

