#!/usr/bin/perl
#
## $Id: menu.pl,v 8.23 2012/08/13 05:05:00 keiths Exp $
#
#  Copyright (C) Opmantek Limited (www.opmantek.com)
#
#  ALL CODE MODIFICATIONS MUST BE SENT TO CODE@OPMANTEK.COM
#
#  This file is part of Network Management Information System ("NMIS").
#
#  NMIS is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  NMIS is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with NMIS (most likely in a file named LICENSE).
#  If not, see <http://www.gnu.org/licenses/>
#
#  For further information on NMIS or for a license other than GPL please see
#  www.opmantek.com or email contact@opmantek.com
#
#  User group details:
#  http://support.opmantek.com/users/
#
# *****************************************************************************
use FindBin;
use lib "$FindBin::Bin/../lib";
use Data::Dumper;

use Compat::NMIS;
use NMISNG::Util;
use Compat::Modules;

use JSON::XS;

use CGI qw(:standard *table *Tr *td *form *Select *div);

my $q = new CGI; # This processes all parameters passed via GET and POST
my $Q = $q->Vars; # values in hash

# load NMIS configuration table
my $C = NMISNG::Util::loadConfTable(debug=>$Q->{debug});

# set some defaults
my $widget_refresh = $C->{widget_refresh_time} ? $C->{widget_refresh_time} : 180 ;

# NMIS Authentication module
use NMISNG::Auth;

# variables used for the security mods
my $headeropts = {type=>'text/html',expires=>'now'};
my $AU = NMISNG::Auth->new(conf => $C);

if ($AU->Require) {
	exit 0 unless $AU->loginout(type=>$Q->{auth_type},username=>$Q->{auth_username},
					password=>$Q->{auth_password},headeropts=>$headeropts) ;
	$user = $AU->{user};
}

# dispatch the request
if ($Q->{act} eq 'menu_bar_site') {			menu_bar_site(); # vertical parent menu
} elsif ($Q->{act} eq 'menu_bar_portal') {	menu_bar_portal(); # hr portal select
} elsif ($Q->{act} eq 'menu_about_view') {	menu_about_view();
} elsif ( exists ($Q->{POSTDATA}) ) {	save_window_state();
} else { notfound(); }

sub notfound {
	print header({-type=>"text/html",-expires=>'now'});
	print "Menu; ERROR, act=$Q->{act}<br> \n";
	print "Request not found\n";
}

#============================================================================


# print the menu in boring HTML <ul><li>
# CGI ::Pretty would not format this  so I hardcoded the ident and recurse level to verify correct operation
# remove for production .
# this is a recursive function
# needs a tidyup..TBD
sub print_array_list {
	my $aref = shift;
	my $level = shift;
	my $arrow = shift;				# flag to print the directional arrow
	my $a = [];

	my $ident;
	foreach ( 0 .. $level) { $ident.='  '};


	while ( defined ( $a = shift @{$aref}) ) {
		if ( not ref $a ) {
			# current is a  header or item string
			# add the onclick handler if a href (ie) dont jquery it later, ccheaper and easier to cleanup here
			# ignore any links that have a 'target' attribute
			if ( $a =~ /href=/i and $a !~ /target/i ) {
				substr($a, index($a, '<a '), 3) = qq|<a onClick="clickMenu(this);return false" |;
			}
			# lookahead and test if the next arg is a string or ref
			# if a ref, dont add end_li tag, else wrap this in <li>xx</li>
			if ( not scalar @{$aref} ) {
				# finished the list
				print "$ident<li>$a</li>\n";
			}
			elsif ( not ref $aref->[0] ) {					# look ahead to the next item on the list
				# next is a list item
				print "$ident<li>$a</li>\n";
			}
			else {
				# next is a ref, so dont complete </li>
				# so we recurse and come back shortly
				print "$ident<li>$a";
			}
		}
		else {							# we have a reference, so recurse to it
			my $id = $level;
			$id++;
			my $id2;
			foreach ( 0 .. $id) { $id2.='  '};
			# print  the directional arrow first.
			if ( $arrow) { print qq|<img style="vertical-align:middle;" src="$C->{'<menu_url_base>'}/img/arrow_right_black.gif">|; }
			print "\n<ul>\n";		# and wrap it in a <ul>...</ul> tags
			print_array_list( $a, $id+1, 1 );					# recursive - pass the aref to ourslves
			print "</ul>\n$ident</li>\n";			#  arrow is printed on al sub menus
		}
	}
}


# VERTICAL SIDEBAR menu
# I have set these up as 'push @x, list of arrays
# format is
# menu[0] = ref to anon list( 'header string', ref to submenu items  );
# menu[1] = ref to anon list( 'header string', ref to submenu items  );
# a nested menu
# menu[2] = ref to anon list( 'header string', ( ref to anon list( 'header string', ref to submenu items  ));
#
# These are hardcoded here as a development exercise
# in reality the menu arrays should be generated by the user auth modules
# as that will provide a list of menu buttons, based on user rights

sub menu_bar_site {

	print header({-type=>"text/html",-expires=>'now'});
	print		$q->start_ul({ class=>"jd_menu"});
	print_array_list( menu_site(), 1 , 0 );
	print $q->end_ul();


	sub menu_site
	{
		my $M = Compat::Modules->new(nmis_base => $C->{'<nmis_base>'},
													 nmis_cgi_url_base => $C->{'<cgi_url_base>'});
		my $modules = $M->getModules();

		my @menu_site = [];

		my @netstatus;
		push @netstatus, qq|<a id='ntw_metrics' href="network.pl?refresh=$widget_refresh&amp;act=network_summary_metrics">Metrics</a>|;
		push @netstatus, qq|<a id='ntw_graph' href="network.pl?refresh=$widget_refresh&amp;act=network_metrics_graph">Network Metric Graphs</a>|;
		push @netstatus, qq|<a id='ntw_view' href="network.pl?refresh=$widget_refresh&amp;act=network_summary_view">Network Metrics and Health</a>|;
		push @netstatus, qq|<a id='ntw_health' href="network.pl?refresh=$widget_refresh&amp;act=network_summary_health">Network Status and Health</a>|;
		push @netstatus, qq|<a id='ntw_summary' href="network.pl?refresh=$widget_refresh&amp;act=network_summary_large">Network Status and Health by Group</a>|;

		push @netstatus, qq|<a id='ntw_services' href="services.pl?">Monitored Services</a>|;
		push @netstatus, qq|<a id='src_events' href="events.pl?act=event_table_list">Current Events</a>|
				if ($AU->CheckAccess("tls_event_db","check"));

		push @netstatus, qq|<a id='nmislogs' href="logs.pl?act=log_file_view&amp;lines=50">Network Events</a>|
						if ($AU->CheckAccess("Event_Log","check"));

		push @netstatus, qq|<a id='ntw_customer' href="network.pl?refresh=$widget_refresh&amp;act=network_summary_customer">Customer Status and Health</a>| if Compat::NMIS::tableExists('Customers');
		push @netstatus, qq|<a id='ntw_business' href="network.pl?refresh=$widget_refresh&amp;act=network_summary_business">Business Services Status and Health</a>| if Compat::NMIS::tableExists('BusinessServices');
		push @netstatus, qq|<a id='selectNode_open' onclick="selectNodeOpen();return false;">Quick Search</a>|;
		push @netstatus, qq|<a id='ntw_rss' href="community_rss.pl?widget=true">NMIS Community</a>|;

		push @menu_site,(qq|Network Status|,[ @netstatus ]);


		my @netperf;
		push @netperf, qq|<a id='ntw_overview' href="network.pl?refresh=$widget_refresh&amp;act=network_summary_allgroups">All Groups</a>|;
		push @netperf, qq|<a id='ntw_overview' href="network.pl?refresh=$widget_refresh&amp;act=network_interface_overview">OverView</a>|;
		push @netperf, qq|<a id='ntw_top10' href="network.pl?refresh=$widget_refresh&amp;act=network_top10_view">Top 10</a>|;

		push @netperf, qq|<a id='ntw_links' href="tables.pl?act=config_table_menu&amp;table=Links">Link List</a>|
								if ($AU->CheckAccess("Table_Links_view","check"));

		push @menu_site,(qq|Network Performance|,[ @netperf ]);


		#Handling optional items in the menu, depending on the config.
		my @nettools;
		push @nettools, qq|<a id='tools_ping' href="tools.pl?act=tool_system_ping">Ping</a>|;
		push @nettools, qq|<a id='tools_trace' href="tools.pl?act=tool_system_trace">Traceroute</a>|;
		push @nettools, qq|<a id='tools_lft' href="tools.pl?act=tool_system_lft">LFT</a>| if (NMISNG::Util::getbool($C->{view_lft}));
		push @nettools, qq|<a id='tools_mtr' href="tools.pl?act=tool_system_mtr">MTR</a>| if (NMISNG::Util::getbool($C->{view_mtr}));
		push @nettools, qq|<a id='tls_snmp' href="snmp.pl?act=snmp_var_menu">SNMP Tool</a>|;


		my @netitems;
		push @netitems, qq|<a id='tls_ip' href="ip.pl?act=tool_ip_menu">IP Calc</a>|,
		qq|<a id='tls_dns_host' href="tools.pl?act=tool_system_dns&amp;dns=host">IP host</a>|,
		qq|<a id='tls_dns_dns' href="tools.pl?act=tool_system_dns&amp;dns=dns">IP dns</a>|,
		qq|<a id='tls_dns_arpa' href="tools.pl?act=tool_system_dns&amp;dns=arpa">IP arpa</a>|,
		qq|<a id='tls_dns_loc' href="tools.pl?act=tool_system_dns&amp;dns=loc">IP loc</a>|
				if ($AU->CheckAccess("tls_dns","check"));

		push @nettools,	qq|IP Tools|, \@netitems if (@netitems);

		push @menu_site,(qq|Network Tools|,[ @nettools ]);

		# Potential Future Capabilities
		#push @menu_site,	( qq|Business Dashboard|);
		#push @menu_site,	( qq|Applications Dashboard|);

		my @reports;
		#push @reports, qq|<a id='opReports' href="$modules->{opReports}{link}?widget=true">opReports</a>| if $M->moduleInstalled(module => "opReports");

		my @flavours=(qw(Current dynamic dyn History stored strd));
		while (@flavours)
		{
				my $long = shift @flavours;
				my $short = shift @flavours;
				my $accesskey = shift @flavours;

				my @details=("avail","Availability","available",
										 "health","Health","health",
										 "times","Collect/Update Time","times",
										 "response","Response Time","response",
										 "top10","Top 10","top10",
										 "outage","Outage","outage",
										 "port","Port Counts","port");
				my @localrep;
				while (@details)
				{
						my $repkey = shift @details;
						my $replabel = shift @details;
						my $accesssub = shift @details;

						push @localrep, qq|<a id='${short}_$repkey' href="reports.pl?act=report_${short}_${repkey}">$replabel</a>|
								if ($AU->CheckAccess("${accesskey}_${accesssub}","check"));
				}

				push @reports, $long, \@localrep if (@localrep);
		}

		push @menu_site,(qq|Reports|,[ @reports ]) if (@reports);

		# Potential Future Capabilities
		#push @menu_site,	( qq|Traffic Monitor|,
		#										[
		#											qq|<a id='tm_netflow' href="#">NetFlow</a>|
		#										]
		#									);

		my @stuff;
		push @stuff, qq|<a id='src_events' href="events.pl?act=event_table_list">Events</a>|
				if ($AU->CheckAccess("tls_event_db","check"));
		push @stuff, qq|<a id='src_outages' href="outages.pl?act=outage_table_view">Outages</a>|;
		push @stuff, qq|<a id='src_links' href="tables.pl?act=config_table_menu&amp;table=Links">Links</a>|
								if ($AU->CheckAccess("Table_Links_view","check"));

		my @logstuff;
		push @logstuff, qq|<a id='nmislogs' href="logs.pl?act=log_file_view&amp;logname=NMIS_Log">NMIS Log</a>|
				if ($AU->CheckAccess("NMIS_Log","check"));
		push @logstuff, qq|<a id='eventlogs' href="logs.pl?act=log_file_view">Event Log</a>|
				if ($AU->CheckAccess("Event_Log","check"));
		push @logstuff, qq|<a id='nmislogs' href="logs.pl?act=log_list_view">Log List</a>|
				if ($AU->CheckAccess("log_list","check"));

		my @sdeskstuff;
		push @sdeskstuff, qq|Alerts|, \@stuff if (@stuff);
		push @sdeskstuff, qq|Find|,
		[
				qq|<a id='find_node' href="find.pl?act=find_node_menu">Node</a>|,
				qq|<a id='find_interface' href="find.pl?act=find_interface_menu">Interface</a>|
		];
		push @sdeskstuff, qq|Logs|, \@logstuff if (@logstuff);

		push @sdeskstuff, qq|Monitored Services|, [ qq|<a id='ntw_services' href="services.pl?">All Services</a>|,
																								qq|<a id='ntw_services_ok' href="services.pl?only_show=ok">Only running Services</a>|,
																								qq|<a id='ntw_services_notok' href="services.pl?only_show=notok">Only Services with Problems</a>| ];

		push @menu_site, qq|Service Desk|, \@sdeskstuff;

		my $Tables = Compat::NMIS::loadGenericTable('Tables');

		my @tableMenu;

		push @tableMenu, qq|<a id='cfg_nodes' href="tables.pl?act=config_table_menu&amp;table=Nodes">NMIS Nodes (devices)</a>|
				if ($AU->CheckAccess("Table_Nodes_view","check"));

		push @tableMenu, qq|<a id='cfg_nmis' href="config.pl?act=config_nmis_menu">NMIS Configuration</a>|
				if ($AU->CheckAccess("table_config_view","check"));

		push @tableMenu, qq|<a id='cfg_models' href="models.pl?act=config_model_menu">NMIS Models</a>|
				if ($AU->CheckAccess("table_models_view","check"));

		push @tableMenu, qq|<a id='cfg_nodecfg' href="nodeconf.pl?act=config_nodeconf_view">Node Configuration</a>|
				if ($AU->CheckAccess("table_nodeconf_view","check"));

		push @tableMenu, qq|<a id='cfg_modelpolicy' href="model_policy.pl?">Model Policy</a>|
				if ($AU->CheckAccess("table_models_view","check"));

		push @tableMenu,	qq|<a id='cfg_hidegroups' href="config.pl?act=config_nmis_edit&amp;section=system&amp;item=hide_groups">Hide Groups</a>|
				if ($AU->CheckAccess("table_config_view","check"));


		push @tableMenu, qq|------| if (@tableMenu); # no separator if there's nothing to separate...

		foreach my $table (sort {$Tables->{$a}{DisplayName} cmp $Tables->{$b}{DisplayName} } keys %{$Tables}) {
			push @tableMenu, qq|<a id="cfg_$table" href="tables.pl?act=config_table_menu&amp;table=$table">$Tables->{$table}{DisplayName}</a>| if ($table ne "Nodes" and $AU->CheckAccess("Table_${table}_view","check"));
		}

		my (@systemitems, @setupitems);



		push @systemitems, qq|System Configuration|, \@tableMenu if (@tableMenu);

		if ($AU->CheckAccess("tls_event_flow","check")
				or $AU->CheckAccess("Table_Nodes_view","check"))
		{
			my @submenu;

			push @submenu, qq|<a id='cfg_setup' href="network.pl?act=node_admin_summary">Node Admin Summary</a>| if ($AU->CheckAccess("Table_Nodes_view","check"));

			push @submenu, 	qq|<a id='tls_event_flow' href="view-event.pl?act=event_flow_view">Check Event Flow</a>|,
			qq|<a id='tls_event_db' href="view-event.pl?act=event_database_list">Check Event DB</a>| if ($AU->CheckAccess("tls_event_flow","check"));

			push @systemitems, qq|Configuration Check|, \@submenu;
		}

		my @hostdiags;
		if ($AU->CheckAccess("tls_nmis_runtime", "check"))
		{
			push @hostdiags, qq|<a id='nmis_selftest' href="network.pl?refresh=$widget_refresh&amp;act=nmis_selftest_view">NMIS Selftest</a>|,
			qq|<a id='nmis_poll' href="network.pl?act=nmis_polling_summary">NMIS Polling Summary</a>|,
			qq|<a id='nmis_run' href="network.pl?refresh=$widget_refresh&amp;act=nmis_runtime_view">NMIS Runtime Graph</a>|;
		};
		push @hostdiags, qq|<a id='tls_host_info' href="tools.pl?act=tool_system_hostinfo">NMIS Host Info</a>|;

		push @hostdiags, qq|<a id="nmis_opstatus" href="opstatus.pl?">NMIS Ops Status</a>|;

		for my $cmd (qw(date df ps iostat vmstat who))
		{
				push @hostdiags, qq|<a id='tls_$cmd' href="tools.pl?act=tool_system_$cmd">$cmd</a>|
						if ($AU->CheckAccess("tls_$cmd","check"));
		}
		push @systemitems, qq|Host Diagnostics|, \@hostdiags if (@hostdiags);

		push @setupitems, qq|<a id='cfg_setup' href="setup.pl?act=setup_menu">Basic Setup</a>|
				if ($AU->CheckAccess("table_config_view","check"));

		# no separator if there's nothing to separate...
		push @setupitems, qq|           | if (@setupitems);

		push @setupitems, qq|--- Advanced Setup ---| if (@setupitems); # no separator if there's nothing to separate...

		push @setupitems,	qq|<a id='cfg_ntypes' href="config.pl?act=config_nmis_edit&amp;section=system&amp;item=nodetype_list">Add/Edit Node Types</a>|
				if ($AU->CheckAccess("table_config_view","check"));

		push @setupitems,	qq|<a id='cfg_nroles' href="config.pl?act=config_nmis_edit&amp;section=system&amp;item=roletype_list">Add/Edit Node Roles</a>|
				if ($AU->CheckAccess("table_config_view","check"));

		push @setupitems,	qq|<a id='cfg_nettypes' href="config.pl?act=config_nmis_edit&amp;section=system&amp;item=nettype_list">Add/Edit Network Types</a>|
				if ($AU->CheckAccess("table_config_view","check"));

		push @setupitems, qq|<a id='cfg_nodes' href="tables.pl?act=config_table_add&amp;table=Nodes">Add/Edit Nodes and Devices</a>|
				if ($AU->CheckAccess("Table_Nodes_view","check"));

		push @setupitems, qq|<a id='cfg_nodecfg' href="nodeconf.pl?act=config_nodeconf_view">Node Customisation</a>|
				if ($AU->CheckAccess("table_nodeconf_view","check"));

		push @setupitems, qq|<a id="cfg_Contacts" href="tables.pl?act=config_table_menu&amp;table=Contacts">Contact Setup</a>|
				if ($AU->CheckAccess("Table_Escalations_view","check"));

		push @setupitems, qq|<a id="cfg_Escalations" href="tables.pl?act=config_table_menu&amp;table=Escalations">Emails, Notifications and Escalations</a>|
				if ($AU->CheckAccess("Table_Escalations_view","check"));

		push @setupitems, qq|<a id="cfg_Events" href="tables.pl?act=config_table_menu&amp;table=Events">Event Configuration</a>|
				if ($AU->CheckAccess("Table_Events_view","check"));

		push @setupitems, qq|<a id="cfg_models" href="models.pl?act=config_model_menu&amp;model=Common-threshold&amp;section=threshold">Thresholding Alert Tuning</a>|
				if ($AU->CheckAccess("table_models_view","check"));

		push @setupitems, qq|<a id='cfg_modelpolicy' href="model_policy.pl?">Model Policy</a>|
				if ($AU->CheckAccess("table_models_view","check"));

		push @setupitems, qq|<a id='cfg_pollingpolicy' href="tables.pl?act=config_table_menu&amp;table=Polling-Policy">Polling Policy</a>|
				if ($AU->CheckAccess("table_polling-policy_view","check"));

		#push @setupitems, qq|<a id="cfg_models" href="models.pl?act=config_model_menu&amp;model=Default&amp;section=event">Event Logging and Syslog</a>|
		#		if ($AU->CheckAccess("table_models_view","check"));

		push @menu_site, qq|Setup|, \@setupitems if (@setupitems);

		push @menu_site, qq|System|, \@systemitems if (@systemitems);

		# Moved Quick Search to network status and do not need NMIS Server anymore.
		#push @menu_site,( qq|Quick Select|,
		#										[	qq|<a id='selectServer_open' onclick="selectServerDisplay();return false;">NMIS Server</a>|,
		#											qq|<a id='selectNode_open' onclick="selectNodeOpen();return false;">Quick Search</a>|
		#										]
		#								);

		push @menu_site,( qq|Windows|,
												[	qq|<a id='saveWindow_open' onclick="saveWindowState();return false;">Save Windows and Positions</a>|,
													qq|<a id='clearWindow_open' onclick="clearWindowState();return false;">Clear Windows and Positions</a>|
												]
										);

		push @menu_site,( qq|Help|,
												[	qq|<a id='hlp_help' target='_blank' href="http://www.opmantek.com">NMIS</a>|,
													qq|<a id='hlp_apache' target='_blank' href="http://www.apache.org" id='apache'>Apache</a>|,
													qq|<a id='hlp_about' href="menu.pl?act=menu_about_view">About</a>|
												]
										);
		return \@menu_site;
	}
}
	#==============================

# HORIZANTAL Menu - home and client tags

sub menu_bar_portal {

	# take this to config.xxxx.!
	# portal menu of nodes or clients to link to.

	print header({-type=>"text/html",-expires=>'now'});
	print		$q->start_ul({ class=>"jd_menu"});
	print_array_list( menu_portal(), 1 , 0 );
	print $q->end_ul();


	sub menu_portal {
		my @menu_portal = [];
				push @menu_portal,	( qq|<a href="nmiscgi.pl?" target='_self'>NMIS9 Home</a>|);
				push @menu_portal,	( qq|Client Views|,
												[
# fixme9: none of this works with nmis9
# 		 qq|<a href="http://master.domain.com/cgi-master/nmiscgi.pl" target='_blank'>NMIS4 Demo Master/Slave</a>|,
#												  qq|<a href="#" >Customer A</a>|,
#												   qq|<a href="#" >Customer B</a>|
#
												]);

		return [ @menu_portal ];
	}
}


#==============================

sub menu_about_view {
	print header({-type=>"text/html",-expires=>'now'});
	print table(Tr(td({class=>'info'},<<EO_TEXT)));
<br/>
Network Management Information System<br/>
NMIS Version $Compat::NMIS::VERSION<br/>
Copyright (C) <a href="https://opmantek.com">Opmantek Limited (www.opmantek.com)</a><br/>
This program comes with ABSOLUTELY NO WARRANTY;<br/>
This is free software licensed under GNU GPL, and you are welcome to<br/>
redistribute it under certain conditions; see <a href="https://opmantek.com">opmantek.com</a> or email<br/>
 <a href="mailto:contact\@opmantek.com">contact\@opmantek.com<br/>

EO_TEXT

}

# read table of window states, update this user's entry, then write it
# out again
sub save_window_state {
	my $data = $Q->{POSTDATA};
	my $windowData = decode_json($data);
	my ($allWindowData, $handle) = NMISNG::Util::loadTable(dir => 'var',
																					 name => "nmis-windowstate",
																					 lock =>  'true');
	$allWindowData->{$user} = $windowData->{windowData};

	NMISNG::Util::writeTable(dir=>'var', name=>"nmis-windowstate", data=>$allWindowData,
			handle => $handle);

	print header({-type=>"text/html",-expires=>'now'});
	print table(Tr(td({class=>'info'},<<EO_TEXT)));
<br/>
Success
EO_TEXT
	return;
}
# *****************************************************************************
# Copyright (C) Opmantek Limited (www.opmantek.com)
# This program comes with ABSOLUTELY NO WARRANTY;
# This is free software licensed under GNU GPL, and you are welcome to
# redistribute it under certain conditions; see www.opmantek.com or email
# contact@opmantek.com
# *****************************************************************************
