#!/usr/bin/perl
# a small NMIS service helper script for testing Atlassian Jira
# for recent activity
#
# args: JIRA BASE url, ie. just schema://host:port/
# -u, -p user's username and password
# -j JQL query (optional)
#
# exits with 100 if all ok
# 0 if jira was not reachable at all,
# 10 if the credentials didn't work
# 20 if the jql was dud
# 30 if there was no activity
our $VERSION = "1.0.0";

use strict;
use URI;
use LWP::UserAgent;

use JSON::XS;
use POSIX;
use Getopt::Std;

my %opts;
die "Usage: $0 [-Nd] [-j JQL] {-u user} {-p passwd} <url>
-N: do NOT check ssl certificates
-d: produce debug output on STDERR
-j: use this JQL query
\n\n"
		if (!getopts("u:p:Ndj:",\%opts) or !$opts{u} or !$opts{p} or @ARGV != 1);

my $username = $opts{u};
my $password = $opts{p};
my $jql = $opts{j} || 'created >= -24h OR updated >= -24h';

my $jiraurl = URI->new($ARGV[0]);

my $exitcode = 0;

my $ua = LWP::UserAgent->new;
$ua->timeout(10);
$ua->env_proxy();

$jiraurl->path("rest/api/2/search");
$jiraurl->query_form("jql" => $jql, "fields" => "key,id");

my $req = HTTP::Request->new(GET => $jiraurl);
$req->header("Accept" => "application/json");
$req->header("Content-Type" => "application/json");
$req->authorization_basic($username, $password);

my $res = $ua->request($req);
print STDERR "response for was ".$res->decoded_content."\n" if ($opts{d});

if ($res->code == 403)
{
	$exitcode = 10;								# auth dud
}
elsif ($res->is_success)
{
	$exitcode = 20;
	my $rdata = eval { decode_json($res->decoded_content) };
	if (!$@)
	{
		$exitcode = 30 if (!$rdata->{errorMessages});
		$exitcode = 100 if ($rdata->{total});
	}
}

exit $exitcode;

