## For more information on the listed Apache features please consult:
## http://httpd.apache.org/docs/

# Don't forget to restart the daemon if you make changes to this configuration file1
# apachectl restart

<IfModule mod_proxy.c>
ProxyRequests off

<IfModule mod_headers.c>
# if you are using the Opmantek applications behind an ssl-terminating apache vhost,
# then you should adjust the vhost configuration to add this header but with 
# protocol "https". 
# The Opmantek applications are location- and protocol-independent in almost all cases.
RequestHeader set X-Forwarded-Proto "http"
</IfModule>

<Location "/omk">
    ProxyPass http://nmis:8042/omk retry=5
    ProxyPassReverse http://nmis:8042/omk
		ErrorDocument 503 '<html><head><meta http-equiv="refresh" content="60"></head><body><h1>Temporary Service Interruption</h1>The requested OMK page should be back soon. This page will automatically reload in 60 seconds.</body></html>'
</Location>

# the first location directive only covers /omk and /omk/something,
# not /omk.json
<Location "/omk.json">
    ProxyPass http://nmis:8042/omk.json retry=5
    ProxyPassReverse http://nmis:8042/omk.json
</Location>


<Location "/es">
    ProxyPass http://nmis:8042/es retry=5
    ProxyPassReverse http://nmis:8042/es
		ErrorDocument 503 '<html><head><meta http-equiv="refresh" content="60"></head><body><h1>Temporary Service Interruption</h1>The requested OMK page should be back soon. This page will automatically reload in 60 seconds.</body></html>'
</Location>

<Location "/en">
    ProxyPass http://nmis:8042/en retry=5
    ProxyPassReverse http://nmis:8042/en
		ErrorDocument 503 '<html><head><meta http-equiv="refresh" content="60"></head><body><h1>Temporary Service Interruption</h1>The requested OMK page should be back soon. This page will automatically reload in 60 seconds.</body></html>'
</Location>

<Location "/pt">
    ProxyPass http://nmis:8042/pt retry=5
    ProxyPassReverse http://nmis:8042/pt
		ErrorDocument 503 '<html><head><meta http-equiv="refresh" content="60"></head><body><h1>Temporary Service Interruption</h1>The requested OMK page should be back soon. This page will automatically reload in 60 seconds.</body></html>'
</Location>

</IfModule>
