name: Docker Dev Build

on:
  push:
    branches: [ docker_dev_actions_test ]

jobs:
  build_docker_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lint dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker-dev/dockerfile-dev
          config: docker-dev/.hadolint.yaml

      - name: Install pre-requisite packages
        run : |
          sudo apt-get update
          sudo apt-get install -y snmp snmpd

      - name: Get NMIS version
        id: version
        run: | 
          VERSION=$(grep 'our $VERSION' lib/NMISNG.pm | sed 's/.*"\([0-9.]*\)".*/\1/')
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo -e "\nVERSION=$VERSION" >> docker-dev/.env-dev

      - name: Build NMIS image
        run: |
          docker build -t nmis-dev:${VERSION} -f docker-dev/dockerfile-dev .
          docker image ls
      
      - name: Compose up NMIS container
        run: |
          docker compose -f docker-dev/compose-dev.yaml --env-file docker-dev/.env-dev up -d
          docker ps
          NMIS_CONT_NAME=$(docker ps --format "{{.Names}}" | grep nmis-1)
          echo "NMIS_CONT_NAME=$NMIS_CONT_NAME" >> "$GITHUB_ENV"
          echo "$NMIS_CONT_NAME"
          sleep 30
      
      - name: Run Docker unit tests
        run : |
          echo "${NMIS_CONT_NAME}"
          docker exec ${NMIS_CONT_NAME} /bin/bash -c "/usr/local/nmis9/docker-dev/docker_tests.sh"

      - name: Compose down NMIS container
        run: |
          docker compose -f docker-dev/compose-dev.yaml down